"""empty message

Revision ID: 25dbaa542221
Revises: 428e9c78cde1
Create Date: 2016-01-20 21:23:37.052664

"""

# revision identifiers, used by Alembic.
revision = '25dbaa542221'
down_revision = '428e9c78cde1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
