"""empty message

Revision ID: 2b8e6501ba0c
Revises: None
Create Date: 2016-02-05 08:12:50.551975

"""

# revision identifiers, used by Alembic.
revision = '2b8e6501ba0c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
