"""initial migration

Revision ID: 3ba4a1679add
Revises: None
Create Date: 2016-01-14 10:27:09.439124

"""

# revision identifiers, used by Alembic.
revision = '3ba4a1679add'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
