"""empty message

Revision ID: 448427b675f2
Revises: None
Create Date: 2016-02-06 09:49:11.520716

"""

# revision identifiers, used by Alembic.
revision = '448427b675f2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
