"""empty message

Revision ID: 538fcc498653
Revises: 448427b675f2
Create Date: 2016-02-20 08:22:50.920250

"""

# revision identifiers, used by Alembic.
revision = '538fcc498653'
down_revision = '448427b675f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
