"""empty message

Revision ID: 7f16910ad2c
Revises: 15e9c101e9ce
Create Date: 2016-02-24 20:07:16.011416

"""

# revision identifiers, used by Alembic.
revision = '7f16910ad2c'
down_revision = '15e9c101e9ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
